/**
 * Agent chat state store.
 *
 * Each tab has its own independent agent state, allowing multiple
 * concurrent chat sessions across tabs. The AgentState is passed
 * directly as a prop through the component chain.
 */

import type { AcpProviderInfo } from '../services/ai';

export type AcpProvider = 'goose' | 'claude';

/**
 * A saved artifact from an agent conversation.
 * Artifacts are markdown documents generated by the agent that the user
 * explicitly saves (e.g., plans, summaries, analysis results).
 */
export interface Artifact {
  id: string;
  title: string;
  content: string;
  createdAt: string;
}

/**
 * State for a single agent chat session.
 * Each tab gets its own instance.
 */
export interface AgentState {
  input: string;
  response: string;
  loading: boolean;
  error: string;
  sessionId: string | null;
  provider: AcpProvider;
  /** Saved artifacts from this session */
  artifacts: Artifact[];
}

/**
 * Global state shared across all tabs (provider discovery).
 */
export const agentGlobalState = $state({
  availableProviders: [] as AcpProviderInfo[],
  providersLoaded: false,
});

/**
 * Create a fresh agent state for a new tab.
 */
export function createAgentState(): AgentState {
  return {
    input: '',
    response: '',
    loading: false,
    error: '',
    sessionId: null,
    provider: 'goose',
    artifacts: [],
  };
}

/**
 * Generate a unique ID for artifacts.
 */
export function generateArtifactId(): string {
  return crypto.randomUUID();
}
